#!/bin/bash

#
# Build the container image to the local Docker image collection.
#
# Note that this only builds the appropriate image variant for
# the local host, for local testing.
#
docker buildx build --pull \
    --tag=iay/mdq-server-static:latest \
    --output=type=docker \
    .
