#!/bin/bash

#
# Example service creation, including Traefic routing labels.
#
docker service create \
  --name mdq-server-static \
  --hostname mdq-server-static \
  --network traefik \
  --log-driver json-file --log-opt max-size=10m --log-opt max-file=3 \
  --mount type=tmpfs,destination=/opt/mdq-server/logs \
  --constraint node.platform.arch==x86_64 \
  --label traefik.enable=true \
  --label traefik.http.services.mdq-static.loadbalancer.server.port=80 \
  --label traefik.http.routers.mdq-static.entrypoints=web \
  --label "traefik.http.routers.mdq-static.rule=Host(\`md.iay.org.uk\`) && PathPrefix(\`/static\`)" \
  --label traefik.http.routers.mdq-static.service=mdq-static \
  --secret source=mdq-static.crt,target=/opt/mdq-server/creds/signing.crt \
  --secret source=mdq-static.key,target=/opt/mdq-server/creds/signing.key \
  registry.iay.org.uk/mdq-server-static:latest

