#!/bin/bash

#
# Push the latest image, just built, to a private repository.
#
HERE=iay/mdq-server-static:latest
THERE=registry.iay.org.uk/systems/misc/mdq-static:latest

docker tag ${HERE} ${THERE}
docker push ${THERE}
