#!/bin/bash

#
# Build the container image to the private Docker registry.
#
# This builds both image variants for deployment.
#
docker buildx build --pull \
    --platform=linux/amd64,linux/arm64 \
    --tag=registry.iay.org.uk/systems/misc/mdq-static:latest \
    --output=type=registry \
    --builder local \
    .
