#!/usr/bin/env bash

#
# Uncomment the following if the container is directly exposed.
#
#MAP_PORT="-p 80:80"

#
# Which docker network to deploy into. The value here is for my
# own staging server; use "bridge" for the default docker network.
#
NETWORK=nginx-109

docker run -t --rm \
    --name=mdq-server-static --hostname="mdq-server-static" \
	--log-driver json-file --log-opt max-size=10m --log-opt max-file=3 \
    -v `pwd`/logs:/opt/mdq-server/logs \
    -v `pwd`/creds:/opt/mdq-server/creds \
    $MAP_PORT --net=$NETWORK \
    iay/mdq-server-static
