#!/usr/bin/env bash

#
# Acquire the .jar artifact.
#
# This is made available for local testing of deployments using their
# respective "test" scripts.
#
mvn --update-snapshots dependency:copy

# End.
